language: R
sudo: false
cache: packages
install:
  - Rscript -e "install.packages('rmarkdown')"
script:
  - Rscript -e "rmarkdown::render('index.Rmd')"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true

branches:
    - gh-pages    
    - master
